<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\Category;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categories = Category::all();
        
        if ($categories->isEmpty()) {
            $this->command->warn('Không có danh mục nào. Vui lòng chạy CategorySeeder trước.');
            return;
        }

        $getCategoryId = function($name) use ($categories) {
            return $categories->where('name', $name)->first()->id ?? $categories->first()->id;
        };

        $products = [
            // iPhone - 8 sản phẩm
            [
                'category_id' => $getCategoryId('iPhone'),
                'name' => 'iPhone 15 Pro Max 256GB',
                'description' => 'iPhone 15 Pro Max với chip A17 Pro mạnh mẽ nhất, camera 48MP chuyên nghiệp, màn hình 6.7 inch Super Retina XDR sắc nét',
                'specifications' => "Chip: A17 Pro\nRAM: 8GB\nBộ nhớ: 256GB\nMàn hình: 6.7 inch Super Retina XDR\nCamera sau: 48MP + 12MP + 12MP\nCamera trước: 12MP\nPin: 4422 mAh\nSạc: MagSafe, Lightning",
                'price' => 32990000,
                'sale_price' => 29990000,
                'stock' => 50,
                'brand' => 'Apple',
                'color' => 'Titanium tự nhiên',
                'storage' => 256,
                'ram' => 8,
                'screen_size' => '6.7 inch',
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'category_id' => $getCategoryId('iPhone'),
                'name' => 'iPhone 15 Pro Max 512GB',
                'description' => 'iPhone 15 Pro Max phiên bản 512GB, dung lượng lớn cho người dùng chuyên nghiệp',
                'specifications' => "Chip: A17 Pro\nRAM: 8GB\nBộ nhớ: 512GB\nMàn hình: 6.7 inch Super Retina XDR\nCamera sau: 48MP + 12MP + 12MP\nCamera trước: 12MP\nPin: 4422 mAh",
                'price' => 37990000,
                'sale_price' => 34990000,
                'stock' => 30,
                'brand' => 'Apple',
                'color' => 'Titanium xanh',
                'storage' => 512,
                'ram' => 8,
                'screen_size' => '6.7 inch',
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'category_id' => $getCategoryId('iPhone'),
                'name' => 'iPhone 15 Pro 256GB',
                'description' => 'iPhone 15 Pro với chip A17 Pro, kích thước vừa phải 6.1 inch',
                'specifications' => "Chip: A17 Pro\nRAM: 8GB\nBộ nhớ: 256GB\nMàn hình: 6.1 inch Super Retina XDR\nCamera sau: 48MP + 12MP + 12MP\nCamera trước: 12MP\nPin: 3274 mAh",
                'price' => 28990000,
                'sale_price' => 26990000,
                'stock' => 60,
                'brand' => 'Apple',
                'color' => 'Titanium tự nhiên',
                'storage' => 256,
                'ram' => 8,
                'screen_size' => '6.1 inch',
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'category_id' => $getCategoryId('iPhone'),
                'name' => 'iPhone 15 128GB',
                'description' => 'iPhone 15 với chip A16 Bionic, camera 48MP, giá tốt nhất trong dòng iPhone 15',
                'specifications' => "Chip: A16 Bionic\nRAM: 6GB\nBộ nhớ: 128GB\nMàn hình: 6.1 inch Super Retina XDR\nCamera sau: 48MP + 12MP\nCamera trước: 12MP\nPin: 3349 mAh",
                'price' => 22990000,
                'sale_price' => 20990000,
                'stock' => 100,
                'brand' => 'Apple',
                'color' => 'Xanh dương',
                'storage' => 128,
                'ram' => 6,
                'screen_size' => '6.1 inch',
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'category_id' => $getCategoryId('iPhone'),
                'name' => 'iPhone 15 256GB',
                'description' => 'iPhone 15 phiên bản 256GB, đủ dung lượng cho mọi nhu cầu',
                'specifications' => "Chip: A16 Bionic\nRAM: 6GB\nBộ nhớ: 256GB\nMàn hình: 6.1 inch Super Retina XDR\nCamera sau: 48MP + 12MP\nCamera trước: 12MP\nPin: 3349 mAh",
                'price' => 25990000,
                'sale_price' => 23990000,
                'stock' => 80,
                'brand' => 'Apple',
                'color' => 'Hồng',
                'storage' => 256,
                'ram' => 6,
                'screen_size' => '6.1 inch',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => $getCategoryId('iPhone'),
                'name' => 'iPhone 14 Pro 256GB',
                'description' => 'iPhone 14 Pro với chip A16 Bionic, Dynamic Island độc đáo',
                'specifications' => "Chip: A16 Bionic\nRAM: 6GB\nBộ nhớ: 256GB\nMàn hình: 6.1 inch Super Retina XDR\nCamera sau: 48MP + 12MP + 12MP\nCamera trước: 12MP\nPin: 3200 mAh",
                'price' => 24990000,
                'sale_price' => 21990000,
                'stock' => 70,
                'brand' => 'Apple',
                'color' => 'Tím',
                'storage' => 256,
                'ram' => 6,
                'screen_size' => '6.1 inch',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => $getCategoryId('iPhone'),
                'name' => 'iPhone 14 128GB',
                'description' => 'iPhone 14 giá tốt, hiệu năng ổn định với chip A15 Bionic',
                'specifications' => "Chip: A15 Bionic\nRAM: 6GB\nBộ nhớ: 128GB\nMàn hình: 6.1 inch Super Retina XDR\nCamera sau: 12MP + 12MP\nCamera trước: 12MP\nPin: 3279 mAh",
                'price' => 19990000,
                'sale_price' => 17990000,
                'stock' => 120,
                'brand' => 'Apple',
                'color' => 'Xanh',
                'storage' => 128,
                'ram' => 6,
                'screen_size' => '6.1 inch',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => $getCategoryId('iPhone'),
                'name' => 'iPhone 13 128GB',
                'description' => 'iPhone 13 giá rẻ, vẫn còn sức mạnh với chip A15 Bionic',
                'specifications' => "Chip: A15 Bionic\nRAM: 4GB\nBộ nhớ: 128GB\nMàn hình: 6.1 inch Super Retina XDR\nCamera sau: 12MP + 12MP\nCamera trước: 12MP\nPin: 3240 mAh",
                'price' => 15990000,
                'sale_price' => 13990000,
                'stock' => 150,
                'brand' => 'Apple',
                'color' => 'Đỏ',
                'storage' => 128,
                'ram' => 4,
                'screen_size' => '6.1 inch',
                'is_active' => true,
                'is_featured' => false,
            ],

            // Samsung - 8 sản phẩm
            [
                'category_id' => $getCategoryId('Samsung'),
                'name' => 'Samsung Galaxy S24 Ultra 512GB',
                'description' => 'Samsung Galaxy S24 Ultra flagship với bút S Pen, camera 200MP siêu nét',
                'specifications' => "Chip: Snapdragon 8 Gen 3\nRAM: 12GB\nBộ nhớ: 512GB\nMàn hình: 6.8 inch Dynamic AMOLED 2X\nCamera sau: 200MP + 50MP + 12MP + 10MP\nCamera trước: 12MP\nPin: 5000 mAh\nSạc: 45W",
                'price' => 29990000,
                'sale_price' => 27990000,
                'stock' => 30,
                'brand' => 'Samsung',
                'color' => 'Đen Titanium',
                'storage' => 512,
                'ram' => 12,
                'screen_size' => '6.8 inch',
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'category_id' => $getCategoryId('Samsung'),
                'name' => 'Samsung Galaxy S24 Ultra 256GB',
                'description' => 'Samsung Galaxy S24 Ultra phiên bản 256GB, đầy đủ tính năng',
                'specifications' => "Chip: Snapdragon 8 Gen 3\nRAM: 12GB\nBộ nhớ: 256GB\nMàn hình: 6.8 inch Dynamic AMOLED 2X\nCamera sau: 200MP + 50MP + 12MP + 10MP\nCamera trước: 12MP\nPin: 5000 mAh",
                'price' => 26990000,
                'sale_price' => 24990000,
                'stock' => 40,
                'brand' => 'Samsung',
                'color' => 'Titanium vàng',
                'storage' => 256,
                'ram' => 12,
                'screen_size' => '6.8 inch',
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'category_id' => $getCategoryId('Samsung'),
                'name' => 'Samsung Galaxy S24+ 256GB',
                'description' => 'Samsung Galaxy S24+ với màn hình lớn 6.7 inch, hiệu năng mạnh mẽ',
                'specifications' => "Chip: Snapdragon 8 Gen 3\nRAM: 12GB\nBộ nhớ: 256GB\nMàn hình: 6.7 inch Dynamic AMOLED 2X\nCamera sau: 50MP + 10MP + 12MP\nCamera trước: 12MP\nPin: 4900 mAh",
                'price' => 22990000,
                'sale_price' => 20990000,
                'stock' => 50,
                'brand' => 'Samsung',
                'color' => 'Tím',
                'storage' => 256,
                'ram' => 12,
                'screen_size' => '6.7 inch',
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'category_id' => $getCategoryId('Samsung'),
                'name' => 'Samsung Galaxy S24 256GB',
                'description' => 'Samsung Galaxy S24 compact, hiệu năng cao với Snapdragon 8 Gen 3',
                'specifications' => "Chip: Snapdragon 8 Gen 3\nRAM: 8GB\nBộ nhớ: 256GB\nMàn hình: 6.2 inch Dynamic AMOLED 2X\nCamera sau: 50MP + 10MP + 12MP\nCamera trước: 12MP\nPin: 4000 mAh",
                'price' => 19990000,
                'sale_price' => 17990000,
                'stock' => 60,
                'brand' => 'Samsung',
                'color' => 'Đen',
                'storage' => 256,
                'ram' => 8,
                'screen_size' => '6.2 inch',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => $getCategoryId('Samsung'),
                'name' => 'Samsung Galaxy A54 5G 128GB',
                'description' => 'Samsung Galaxy A54 với camera 50MP, màn hình Super AMOLED đẹp mắt',
                'specifications' => "Chip: Exynos 1380\nRAM: 8GB\nBộ nhớ: 128GB\nMàn hình: 6.4 inch Super AMOLED\nCamera sau: 50MP + 12MP + 5MP\nCamera trước: 32MP\nPin: 5000 mAh",
                'price' => 8990000,
                'sale_price' => 7990000,
                'stock' => 150,
                'brand' => 'Samsung',
                'color' => 'Tím',
                'storage' => 128,
                'ram' => 8,
                'screen_size' => '6.4 inch',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => $getCategoryId('Samsung'),
                'name' => 'Samsung Galaxy A34 5G 128GB',
                'description' => 'Samsung Galaxy A34 giá tốt, màn hình Super AMOLED 120Hz',
                'specifications' => "Chip: MediaTek Dimensity 1080\nRAM: 8GB\nBộ nhớ: 128GB\nMàn hình: 6.6 inch Super AMOLED 120Hz\nCamera sau: 48MP + 8MP + 5MP\nCamera trước: 13MP\nPin: 5000 mAh",
                'price' => 6990000,
                'sale_price' => 5990000,
                'stock' => 200,
                'brand' => 'Samsung',
                'color' => 'Xanh',
                'storage' => 128,
                'ram' => 8,
                'screen_size' => '6.6 inch',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => $getCategoryId('Samsung'),
                'name' => 'Samsung Galaxy Z Fold5 512GB',
                'description' => 'Samsung Galaxy Z Fold5 màn hình gập, công nghệ tiên tiến',
                'specifications' => "Chip: Snapdragon 8 Gen 2\nRAM: 12GB\nBộ nhớ: 512GB\nMàn hình: 7.6 inch Dynamic AMOLED 2X (gập)\nCamera sau: 50MP + 10MP + 12MP\nCamera trước: 10MP + 4MP\nPin: 4400 mAh",
                'price' => 39990000,
                'sale_price' => 36990000,
                'stock' => 15,
                'brand' => 'Samsung',
                'color' => 'Đen',
                'storage' => 512,
                'ram' => 12,
                'screen_size' => '7.6 inch',
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'category_id' => $getCategoryId('Samsung'),
                'name' => 'Samsung Galaxy Z Flip5 256GB',
                'description' => 'Samsung Galaxy Z Flip5 màn hình gập dọc, thiết kế độc đáo',
                'specifications' => "Chip: Snapdragon 8 Gen 2\nRAM: 8GB\nBộ nhớ: 256GB\nMàn hình: 6.7 inch Dynamic AMOLED 2X (gập)\nCamera sau: 12MP + 12MP\nCamera trước: 10MP\nPin: 3700 mAh",
                'price' => 22990000,
                'sale_price' => 20990000,
                'stock' => 25,
                'brand' => 'Samsung',
                'color' => 'Tím',
                'storage' => 256,
                'ram' => 8,
                'screen_size' => '6.7 inch',
                'is_active' => true,
                'is_featured' => false,
            ],

            // Xiaomi - 6 sản phẩm
            [
                'category_id' => $getCategoryId('Xiaomi'),
                'name' => 'Xiaomi 14 Pro 512GB',
                'description' => 'Xiaomi 14 Pro với chip Snapdragon 8 Gen 3, camera Leica chuyên nghiệp',
                'specifications' => "Chip: Snapdragon 8 Gen 3\nRAM: 16GB\nBộ nhớ: 512GB\nMàn hình: 6.73 inch AMOLED 120Hz\nCamera sau: 50MP Leica + 50MP + 50MP\nCamera trước: 32MP\nPin: 4880 mAh\nSạc: 120W",
                'price' => 19990000,
                'sale_price' => 17990000,
                'stock' => 40,
                'brand' => 'Xiaomi',
                'color' => 'Đen',
                'storage' => 512,
                'ram' => 16,
                'screen_size' => '6.73 inch',
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'category_id' => $getCategoryId('Xiaomi'),
                'name' => 'Xiaomi 14 256GB',
                'description' => 'Xiaomi 14 compact, hiệu năng cao với Snapdragon 8 Gen 3',
                'specifications' => "Chip: Snapdragon 8 Gen 3\nRAM: 12GB\nBộ nhớ: 256GB\nMàn hình: 6.36 inch AMOLED 120Hz\nCamera sau: 50MP Leica + 50MP + 50MP\nCamera trước: 32MP\nPin: 4610 mAh",
                'price' => 16990000,
                'sale_price' => 14990000,
                'stock' => 50,
                'brand' => 'Xiaomi',
                'color' => 'Xanh',
                'storage' => 256,
                'ram' => 12,
                'screen_size' => '6.36 inch',
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'category_id' => $getCategoryId('Xiaomi'),
                'name' => 'Xiaomi Redmi Note 13 Pro 256GB',
                'description' => 'Xiaomi Redmi Note 13 Pro giá tốt, camera 200MP, hiệu năng mạnh',
                'specifications' => "Chip: Snapdragon 7s Gen 2\nRAM: 12GB\nBộ nhớ: 256GB\nMàn hình: 6.67 inch AMOLED 120Hz\nCamera sau: 200MP + 8MP + 2MP\nCamera trước: 16MP\nPin: 5100 mAh\nSạc: 67W",
                'price' => 7990000,
                'sale_price' => 6990000,
                'stock' => 200,
                'brand' => 'Xiaomi',
                'color' => 'Xanh',
                'storage' => 256,
                'ram' => 12,
                'screen_size' => '6.67 inch',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => $getCategoryId('Xiaomi'),
                'name' => 'Xiaomi Redmi Note 13 128GB',
                'description' => 'Xiaomi Redmi Note 13 giá rẻ, pin trâu 5000mAh',
                'specifications' => "Chip: MediaTek Helio G99\nRAM: 8GB\nBộ nhớ: 128GB\nMàn hình: 6.67 inch AMOLED\nCamera sau: 108MP + 8MP + 2MP\nCamera trước: 16MP\nPin: 5000 mAh\nSạc: 33W",
                'price' => 5990000,
                'sale_price' => 4990000,
                'stock' => 250,
                'brand' => 'Xiaomi',
                'color' => 'Đen',
                'storage' => 128,
                'ram' => 8,
                'screen_size' => '6.67 inch',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => $getCategoryId('Xiaomi'),
                'name' => 'Xiaomi POCO X6 Pro 256GB',
                'description' => 'Xiaomi POCO X6 Pro gaming phone, hiệu năng cực mạnh',
                'specifications' => "Chip: MediaTek Dimensity 8300 Ultra\nRAM: 12GB\nBộ nhớ: 256GB\nMàn hình: 6.67 inch AMOLED 120Hz\nCamera sau: 64MP + 8MP + 2MP\nCamera trước: 16MP\nPin: 5000 mAh\nSạc: 90W",
                'price' => 8990000,
                'sale_price' => 7990000,
                'stock' => 100,
                'brand' => 'Xiaomi',
                'color' => 'Vàng',
                'storage' => 256,
                'ram' => 12,
                'screen_size' => '6.67 inch',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => $getCategoryId('Xiaomi'),
                'name' => 'Xiaomi Redmi 13C 128GB',
                'description' => 'Xiaomi Redmi 13C giá siêu rẻ, phù hợp người dùng cơ bản',
                'specifications' => "Chip: MediaTek Helio G85\nRAM: 6GB\nBộ nhớ: 128GB\nMàn hình: 6.74 inch IPS LCD\nCamera sau: 50MP + 2MP\nCamera trước: 8MP\nPin: 5000 mAh\nSạc: 18W",
                'price' => 3990000,
                'sale_price' => 3490000,
                'stock' => 300,
                'brand' => 'Xiaomi',
                'color' => 'Xanh',
                'storage' => 128,
                'ram' => 6,
                'screen_size' => '6.74 inch',
                'is_active' => true,
                'is_featured' => false,
            ],

            // OPPO - 6 sản phẩm
            [
                'category_id' => $getCategoryId('OPPO'),
                'name' => 'OPPO Find X7 Ultra 512GB',
                'description' => 'OPPO Find X7 Ultra flagship với camera Hasselblad 4 camera',
                'specifications' => "Chip: Snapdragon 8 Gen 3\nRAM: 16GB\nBộ nhớ: 512GB\nMàn hình: 6.82 inch LTPO AMOLED 120Hz\nCamera sau: 50MP Hasselblad + 50MP + 50MP + 50MP\nCamera trước: 32MP\nPin: 5000 mAh\nSạc: 100W",
                'price' => 24990000,
                'sale_price' => 22990000,
                'stock' => 25,
                'brand' => 'OPPO',
                'color' => 'Đen',
                'storage' => 512,
                'ram' => 16,
                'screen_size' => '6.82 inch',
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'category_id' => $getCategoryId('OPPO'),
                'name' => 'OPPO Find X7 256GB',
                'description' => 'OPPO Find X7 với camera Hasselblad, thiết kế cao cấp',
                'specifications' => "Chip: MediaTek Dimensity 9300\nRAM: 16GB\nBộ nhớ: 256GB\nMàn hình: 6.78 inch LTPO AMOLED 120Hz\nCamera sau: 50MP Hasselblad + 50MP + 64MP\nCamera trước: 32MP\nPin: 5000 mAh",
                'price' => 19990000,
                'sale_price' => 17990000,
                'stock' => 35,
                'brand' => 'OPPO',
                'color' => 'Xanh',
                'storage' => 256,
                'ram' => 16,
                'screen_size' => '6.78 inch',
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'category_id' => $getCategoryId('OPPO'),
                'name' => 'OPPO Reno11 256GB',
                'description' => 'OPPO Reno11 với camera chụp ảnh chân dung đẹp, selfie tuyệt vời',
                'specifications' => "Chip: MediaTek Dimensity 7050\nRAM: 12GB\nBộ nhớ: 256GB\nMàn hình: 6.7 inch AMOLED 120Hz\nCamera sau: 50MP + 32MP + 8MP\nCamera trước: 32MP\nPin: 5000 mAh\nSạc: 67W",
                'price' => 9990000,
                'sale_price' => 8990000,
                'stock' => 120,
                'brand' => 'OPPO',
                'color' => 'Xanh ngọc',
                'storage' => 256,
                'ram' => 12,
                'screen_size' => '6.7 inch',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => $getCategoryId('OPPO'),
                'name' => 'OPPO Reno11 128GB',
                'description' => 'OPPO Reno11 phiên bản 128GB, giá tốt hơn',
                'specifications' => "Chip: MediaTek Dimensity 7050\nRAM: 8GB\nBộ nhớ: 128GB\nMàn hình: 6.7 inch AMOLED 120Hz\nCamera sau: 50MP + 32MP + 8MP\nCamera trước: 32MP\nPin: 5000 mAh",
                'price' => 8990000,
                'sale_price' => 7990000,
                'stock' => 150,
                'brand' => 'OPPO',
                'color' => 'Hồng',
                'storage' => 128,
                'ram' => 8,
                'screen_size' => '6.7 inch',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => $getCategoryId('OPPO'),
                'name' => 'OPPO A79 128GB',
                'description' => 'OPPO A79 giá rẻ, camera selfie 8MP, pin 5000mAh',
                'specifications' => "Chip: MediaTek Helio G99\nRAM: 8GB\nBộ nhớ: 128GB\nMàn hình: 6.72 inch IPS LCD\nCamera sau: 50MP + 2MP\nCamera trước: 8MP\nPin: 5000 mAh\nSạc: 33W",
                'price' => 4990000,
                'sale_price' => 4490000,
                'stock' => 200,
                'brand' => 'OPPO',
                'color' => 'Xanh',
                'storage' => 128,
                'ram' => 8,
                'screen_size' => '6.72 inch',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => $getCategoryId('OPPO'),
                'name' => 'OPPO A58 128GB',
                'description' => 'OPPO A58 entry-level, giá siêu rẻ',
                'specifications' => "Chip: MediaTek Helio G85\nRAM: 6GB\nBộ nhớ: 128GB\nMàn hình: 6.72 inch IPS LCD\nCamera sau: 50MP + 2MP\nCamera trước: 8MP\nPin: 5000 mAh\nSạc: 33W",
                'price' => 3990000,
                'sale_price' => 3490000,
                'stock' => 250,
                'brand' => 'OPPO',
                'color' => 'Đen',
                'storage' => 128,
                'ram' => 6,
                'screen_size' => '6.72 inch',
                'is_active' => true,
                'is_featured' => false,
            ],

            // Vivo - 6 sản phẩm
            [
                'category_id' => $getCategoryId('Vivo'),
                'name' => 'Vivo X100 Pro 512GB',
                'description' => 'Vivo X100 Pro với camera Zeiss, chip MediaTek Dimensity 9300 mạnh mẽ',
                'specifications' => "Chip: MediaTek Dimensity 9300\nRAM: 16GB\nBộ nhớ: 512GB\nMàn hình: 6.78 inch AMOLED 120Hz\nCamera sau: 50MP Zeiss + 50MP + 64MP\nCamera trước: 32MP\nPin: 5400 mAh\nSạc: 100W",
                'price' => 21990000,
                'sale_price' => 19990000,
                'stock' => 35,
                'brand' => 'Vivo',
                'color' => 'Xanh',
                'storage' => 512,
                'ram' => 16,
                'screen_size' => '6.78 inch',
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'category_id' => $getCategoryId('Vivo'),
                'name' => 'Vivo X100 256GB',
                'description' => 'Vivo X100 với camera Zeiss, hiệu năng cao',
                'specifications' => "Chip: MediaTek Dimensity 9300\nRAM: 12GB\nBộ nhớ: 256GB\nMàn hình: 6.78 inch AMOLED 120Hz\nCamera sau: 50MP Zeiss + 50MP + 64MP\nCamera trước: 32MP\nPin: 5000 mAh",
                'price' => 17990000,
                'sale_price' => 15990000,
                'stock' => 45,
                'brand' => 'Vivo',
                'color' => 'Đen',
                'storage' => 256,
                'ram' => 12,
                'screen_size' => '6.78 inch',
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'category_id' => $getCategoryId('Vivo'),
                'name' => 'Vivo Y100 256GB',
                'description' => 'Vivo Y100 với pin lớn 5000mAh, giá tốt',
                'specifications' => "Chip: Snapdragon 695\nRAM: 8GB\nBộ nhớ: 256GB\nMàn hình: 6.38 inch AMOLED\nCamera sau: 50MP + 2MP\nCamera trước: 16MP\nPin: 5000 mAh\nSạc: 44W",
                'price' => 6990000,
                'sale_price' => 5990000,
                'stock' => 180,
                'brand' => 'Vivo',
                'color' => 'Tím',
                'storage' => 256,
                'ram' => 8,
                'screen_size' => '6.38 inch',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => $getCategoryId('Vivo'),
                'name' => 'Vivo Y27 128GB',
                'description' => 'Vivo Y27 giá rẻ, pin trâu, camera 50MP',
                'specifications' => "Chip: MediaTek Helio G85\nRAM: 8GB\nBộ nhớ: 128GB\nMàn hình: 6.64 inch IPS LCD\nCamera sau: 50MP + 2MP\nCamera trước: 8MP\nPin: 5000 mAh\nSạc: 44W",
                'price' => 4990000,
                'sale_price' => 4490000,
                'stock' => 200,
                'brand' => 'Vivo',
                'color' => 'Xanh',
                'storage' => 128,
                'ram' => 8,
                'screen_size' => '6.64 inch',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => $getCategoryId('Vivo'),
                'name' => 'Vivo V29 256GB',
                'description' => 'Vivo V29 với camera selfie 50MP, thiết kế đẹp',
                'specifications' => "Chip: Snapdragon 778G\nRAM: 12GB\nBộ nhớ: 256GB\nMàn hình: 6.78 inch AMOLED 120Hz\nCamera sau: 50MP + 8MP\nCamera trước: 50MP\nPin: 4600 mAh\nSạc: 80W",
                'price' => 10990000,
                'sale_price' => 9990000,
                'stock' => 100,
                'brand' => 'Vivo',
                'color' => 'Hồng',
                'storage' => 256,
                'ram' => 12,
                'screen_size' => '6.78 inch',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => $getCategoryId('Vivo'),
                'name' => 'Vivo Y36 128GB',
                'description' => 'Vivo Y36 entry-level, giá siêu rẻ',
                'specifications' => "Chip: MediaTek Helio G99\nRAM: 8GB\nBộ nhớ: 128GB\nMàn hình: 6.64 inch IPS LCD\nCamera sau: 50MP + 2MP\nCamera trước: 8MP\nPin: 5000 mAh\nSạc: 44W",
                'price' => 4490000,
                'sale_price' => 3990000,
                'stock' => 220,
                'brand' => 'Vivo',
                'color' => 'Đen',
                'storage' => 128,
                'ram' => 8,
                'screen_size' => '6.64 inch',
                'is_active' => true,
                'is_featured' => false,
            ],

            // Realme - 4 sản phẩm
            [
                'category_id' => $getCategoryId('Realme'),
                'name' => 'Realme GT5 Pro 512GB',
                'description' => 'Realme GT5 Pro flagship với Snapdragon 8 Gen 3, sạc nhanh 100W',
                'specifications' => "Chip: Snapdragon 8 Gen 3\nRAM: 16GB\nBộ nhớ: 512GB\nMàn hình: 6.78 inch AMOLED 120Hz\nCamera sau: 50MP + 8MP + 2MP\nCamera trước: 32MP\nPin: 5400 mAh\nSạc: 100W",
                'price' => 16990000,
                'sale_price' => 14990000,
                'stock' => 40,
                'brand' => 'Realme',
                'color' => 'Đen',
                'storage' => 512,
                'ram' => 16,
                'screen_size' => '6.78 inch',
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'category_id' => $getCategoryId('Realme'),
                'name' => 'Realme 12 Pro+ 256GB',
                'description' => 'Realme 12 Pro+ với camera 64MP, giá tốt',
                'specifications' => "Chip: Snapdragon 7s Gen 2\nRAM: 12GB\nBộ nhớ: 256GB\nMàn hình: 6.7 inch AMOLED 120Hz\nCamera sau: 64MP + 8MP + 2MP\nCamera trước: 32MP\nPin: 5000 mAh\nSạc: 67W",
                'price' => 8990000,
                'sale_price' => 7990000,
                'stock' => 120,
                'brand' => 'Realme',
                'color' => 'Xanh',
                'storage' => 256,
                'ram' => 12,
                'screen_size' => '6.7 inch',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => $getCategoryId('Realme'),
                'name' => 'Realme C55 128GB',
                'description' => 'Realme C55 giá rẻ, pin trâu 5000mAh',
                'specifications' => "Chip: MediaTek Helio G88\nRAM: 8GB\nBộ nhớ: 128GB\nMàn hình: 6.72 inch IPS LCD\nCamera sau: 64MP + 2MP\nCamera trước: 8MP\nPin: 5000 mAh\nSạc: 33W",
                'price' => 4990000,
                'sale_price' => 4490000,
                'stock' => 180,
                'brand' => 'Realme',
                'color' => 'Vàng',
                'storage' => 128,
                'ram' => 8,
                'screen_size' => '6.72 inch',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => $getCategoryId('Realme'),
                'name' => 'Realme C53 128GB',
                'description' => 'Realme C53 entry-level, giá siêu rẻ',
                'specifications' => "Chip: Unisoc Tiger T612\nRAM: 6GB\nBộ nhớ: 128GB\nMàn hình: 6.74 inch IPS LCD\nCamera sau: 50MP + 2MP\nCamera trước: 8MP\nPin: 5000 mAh\nSạc: 33W",
                'price' => 3990000,
                'sale_price' => 3490000,
                'stock' => 250,
                'brand' => 'Realme',
                'color' => 'Xanh',
                'storage' => 128,
                'ram' => 6,
                'screen_size' => '6.74 inch',
                'is_active' => true,
                'is_featured' => false,
            ],

            // OnePlus - 3 sản phẩm
            [
                'category_id' => $getCategoryId('OnePlus'),
                'name' => 'OnePlus 12 256GB',
                'description' => 'OnePlus 12 flagship với Snapdragon 8 Gen 3, sạc nhanh 100W',
                'specifications' => "Chip: Snapdragon 8 Gen 3\nRAM: 16GB\nBộ nhớ: 256GB\nMàn hình: 6.82 inch LTPO AMOLED 120Hz\nCamera sau: 50MP + 64MP + 48MP\nCamera trước: 32MP\nPin: 5400 mAh\nSạc: 100W",
                'price' => 19990000,
                'sale_price' => 17990000,
                'stock' => 30,
                'brand' => 'OnePlus',
                'color' => 'Đen',
                'storage' => 256,
                'ram' => 16,
                'screen_size' => '6.82 inch',
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'category_id' => $getCategoryId('OnePlus'),
                'name' => 'OnePlus 12R 256GB',
                'description' => 'OnePlus 12R giá tốt hơn, vẫn có sạc nhanh 100W',
                'specifications' => "Chip: Snapdragon 8 Gen 2\nRAM: 16GB\nBộ nhớ: 256GB\nMàn hình: 6.78 inch AMOLED 120Hz\nCamera sau: 50MP + 8MP + 2MP\nCamera trước: 16MP\nPin: 5500 mAh\nSạc: 100W",
                'price' => 14990000,
                'sale_price' => 12990000,
                'stock' => 50,
                'brand' => 'OnePlus',
                'color' => 'Xanh',
                'storage' => 256,
                'ram' => 16,
                'screen_size' => '6.78 inch',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => $getCategoryId('OnePlus'),
                'name' => 'OnePlus Nord CE 3 256GB',
                'description' => 'OnePlus Nord CE 3 giá tốt, hiệu năng ổn định',
                'specifications' => "Chip: Snapdragon 782G\nRAM: 12GB\nBộ nhớ: 256GB\nMàn hình: 6.7 inch AMOLED 120Hz\nCamera sau: 50MP + 8MP + 2MP\nCamera trước: 16MP\nPin: 5000 mAh\nSạc: 80W",
                'price' => 8990000,
                'sale_price' => 7990000,
                'stock' => 100,
                'brand' => 'OnePlus',
                'color' => 'Xám',
                'storage' => 256,
                'ram' => 12,
                'screen_size' => '6.7 inch',
                'is_active' => true,
                'is_featured' => false,
            ],

            // Huawei - 3 sản phẩm
            [
                'category_id' => $getCategoryId('Huawei'),
                'name' => 'Huawei P60 Pro 512GB',
                'description' => 'Huawei P60 Pro với camera Leica, thiết kế cao cấp',
                'specifications' => "Chip: Snapdragon 8+ Gen 1\nRAM: 12GB\nBộ nhớ: 512GB\nMàn hình: 6.67 inch OLED 120Hz\nCamera sau: 48MP Leica + 48MP + 13MP\nCamera trước: 13MP\nPin: 4815 mAh\nSạc: 88W",
                'price' => 22990000,
                'sale_price' => 20990000,
                'stock' => 20,
                'brand' => 'Huawei',
                'color' => 'Đen',
                'storage' => 512,
                'ram' => 12,
                'screen_size' => '6.67 inch',
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'category_id' => $getCategoryId('Huawei'),
                'name' => 'Huawei Nova 12 256GB',
                'description' => 'Huawei Nova 12 với camera selfie đẹp, giá tốt',
                'specifications' => "Chip: Snapdragon 778G\nRAM: 8GB\nBộ nhớ: 256GB\nMàn hình: 6.7 inch OLED 120Hz\nCamera sau: 50MP + 8MP\nCamera trước: 60MP\nPin: 4500 mAh\nSạc: 66W",
                'price' => 9990000,
                'sale_price' => 8990000,
                'stock' => 80,
                'brand' => 'Huawei',
                'color' => 'Hồng',
                'storage' => 256,
                'ram' => 8,
                'screen_size' => '6.7 inch',
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'category_id' => $getCategoryId('Huawei'),
                'name' => 'Huawei Enjoy 70 128GB',
                'description' => 'Huawei Enjoy 70 giá rẻ, pin lớn',
                'specifications' => "Chip: Snapdragon 680\nRAM: 8GB\nBộ nhớ: 128GB\nMàn hình: 6.75 inch IPS LCD\nCamera sau: 50MP + 2MP\nCamera trước: 8MP\nPin: 6000 mAh\nSạc: 22.5W",
                'price' => 4990000,
                'sale_price' => 4490000,
                'stock' => 150,
                'brand' => 'Huawei',
                'color' => 'Xanh',
                'storage' => 128,
                'ram' => 8,
                'screen_size' => '6.75 inch',
                'is_active' => true,
                'is_featured' => false,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }

        $this->command->info('Đã tạo ' . count($products) . ' sản phẩm mẫu.');
    }
}
